### ISSUE TITLE
Please Add Offsets for German Roms

### ISSUE THREAD

**Issue by Stoned1337** [40Cakes/pokebot-gen3#100]
Can you Implement Support for German Roms? Please.

**Comment by 40Cakes** [comment]
We intend to add support for all languages (eventually) but is not a high priority for now.

**Comment by binary3141** [comment]
Can you Implement Support for chinese Roms? thanks

**Comment by 40Cakes** [comment]
> Can you Implement Support for chinese Roms? thanks

No.
