### ISSUE TITLE
only shutting down, can't open the game

### ISSUE THREAD

**Issue by Dalk2ness** [40Cakes/pokebot-gen3#115]
after my pc are blue screen, bot is gone too. how can i fix it?
![image](https://github.com/40Cakes/pokebot-gen3/assets/10178164/6b4daf4e-74eb-44d3-a032-fbd013373e2b)

**Comment by pekempy** [comment]
Can you video record what happens when you load the bot? There's no "errors" so seeing it ran would help

**Comment by nmurillon** [comment]
I went through the same issue yesterday
I had a random crash while developing a feature, but before crashing, a save was made. So whenever the bot starts, it will try to load this particular save if I'm not mistaken.

Deleting this save solved the problem in my case
