### ISSUE TITLE
Battle - Switching Pokemon error in Ruby 

### ISSUE THREAD

**Issue by johnnieb333** [40Cakes/pokebot-gen3#208]
when the bot goes to switch pokemon in ruby (all I testes so far ) the bot goes to manual and does not switch the pokemon , all mons are high levels battle.yml is set up to rotate and yml is in my profile 
![image](https://github.com/40Cakes/pokebot-gen3/assets/92755174/5b93f548-62c3-4cd1-979c-a1acd90559ed)

**Comment by johnnieb333** [comment]
testes sapphire with no issues then went back to test ruby again and it worked , then tested ruby again and it stopped again it is not consistent

**Comment by pekempy** [comment]
More information from the reporter:

> It tries to switch out and gets stuck on the party menu. 
> I've only used the bot on FR and Ruby. Has been working fine on FR.
> I've attached a save where Whismur has run out of normal moves. It keeps battling with astonish where possible, but tries to switch out of normal types. That's where it gets stuck. Run spin mode and the bug should appear at the first zigzagoon encounter. ~~It seems to switch out fine if the battling pokemon is low on HP though.~~ (scratch that,  it can get stuck there too)
> I have pickup enabled, but no pickup pokemon in the party. I have also noticed it gets stuck trying to collect items from pickup mons. If it helps I can try to reproduce that behaviour and share. 

![image](https://github.com/40Cakes/pokebot-gen3/assets/22874875/d5e1d15a-094d-417c-9ef5-c45b979bf036)
![image](https://github.com/40Cakes/pokebot-gen3/assets/2287487
[example save.zip](https://github.com/40Cakes/pokebot-gen3/files/14094801/example.save.zip)
5/4e4c93d2-bb14-465d-9d8f-1e330550ff6e)
