### ISSUE TITLE
Pickup

### ISSUE THREAD

**Issue by omegadri777** [40Cakes/pokebot-gen3#223]
How do I make the bot to farm items with pickup?

**Comment by pekempy** [comment]
This is covered in the [wiki](https://github.com/40Cakes/pokebot-gen3/tree/main/wiki).
See [Battling & Pickup](https://github.com/40Cakes/pokebot-gen3/blob/main/wiki/pages/Configuration%20-%20Battling%20and%20Pickup.md)

If this has solved your issue, please close this :)

**Comment by omegadri777** [comment]
I modified battle.yml and didn't do anything

**Comment by pekempy** [comment]
Can you please provide a [bit more information](https://github.com/40Cakes/pokebot-gen3/blob/main/wiki/pages/Report%20an%20Issue.md)? 

A screenshot of your `battle.yml` file would help, along with your party, and an explanation of what happens?

We can also support via [Discord](https://discord.com/channels/1057088810950860850/1139190426834833528)

Note, for Pickup ability to trigger, you need to defeat the enemy Pokemon, not just running away from it, so you would need `battle: true` to be set in [battle.yml](https://github.com/40Cakes/pokebot-gen3/blob/15a81df1ecee50fbae19fc9679caaf985e72c1b5/profiles/battle.yml#L9) too.

**Comment by omegadri777** [comment]
I open the bot and it doesn't do anything

**Comment by omegadri777** [comment]
Ah, ok, thanks

**Comment by omegadri777** [comment]
It doesn't kill shinies, right?

**Comment by pekempy** [comment]
Correct, it will switch to [Manual](https://github.com/40Cakes/pokebot-gen3/blob/main/wiki/pages/Mode%20-%20Manual.md) when a shiny Pokemon is encountered unless it is on the [Catch Block List](https://github.com/40Cakes/pokebot-gen3/blob/main/wiki/pages/Configuration%20-%20Catch%20Block%20List.md).

It will also stop for a Pokemon if it has a `return` line underneath its condition in [Custom Catch Filters](https://github.com/40Cakes/pokebot-gen3/blob/main/wiki/pages/Configuration%20-%20Custom%20Catch%20Filters.md)
([Example File](https://github.com/40Cakes/pokebot-gen3/blob/15a81df1ecee50fbae19fc9679caaf985e72c1b5/profiles/customcatchfilters.py#L78)) - so you can see that if a Pokemon has 6 31IV stats, it will switch to manual.

**Comment by omegadri777** [comment]
Thanks for the help, it is working

**Comment by pekempy** [comment]
Glad to help! Feel free to drop in the [Discord](https://discord.com/channels/1057088810950860850/1139190426834833528) if you need any further help :)
