### ISSUE TITLE
FRLG game corner not showing the proper pokemon 

### ISSUE THREAD

**Issue by johnnieb333** [40Cakes/pokebot-gen3#232]
![image](https://github.com/40Cakes/pokebot-gen3/assets/92755174/3b5d0dd8-34de-4dd9-8a70-83eedbd80a5b)
 Scyther is showing up on the bot for both versions , in LG it should be Pinsir , found by mojojack and confirmed by me

**Comment by pekempy** [comment]
Fixed - will be PRd with other bug fixes
