### ISSUE TITLE
Fishing doesnt work whike you are surfing

### ISSUE THREAD

**Issue by Phosky71** [40Cakes/pokebot-gen3#236]
![Captura de pantalla 2024-02-08 215836](https://github.com/40Cakes/pokebot-gen3/assets/98740899/0739d5f9-599c-4c2e-9a2a-7353951f542e)
![Captura de pantalla 2024-02-08 220017](https://github.com/40Cakes/pokebot-gen3/assets/98740899/e8adbd8f-7995-4221-a29b-921b0ea9b351)

**Comment by pekempy** [comment]
As mentioned on the [Wiki](https://github.com/40Cakes/pokebot-gen3/blob/main/wiki/pages/Mode%20-%20Fishing.md#game-support), Non-English ROMs currently are untested/unsupported. 
Unfortunately it looks like fishing is one of those modes which will need language specific support. I've just tested it East of Slateport City and it's working

It works on Emerald (E)
![image](https://github.com/40Cakes/pokebot-gen3/assets/22874875/605fc5f4-de4e-4949-ba6b-9b3cf4510b32)
