### ISSUE TITLE
Auto-pickup enabled

### ISSUE THREAD

**Issue by Phosky71** [40Cakes/pokebot-gen3#245]
![Captura de pantalla 2024-02-13 113715](https://github.com/40Cakes/pokebot-gen3/assets/98740899/da56761e-9c04-46be-82d9-0e1e77f799cf)
Where Can I disable auto-pickup?

**Comment by 40Cakes** [comment]
[Battling and Pickup Config](https://github.com/40Cakes/pokebot-gen3/blob/main/wiki/pages/Configuration%20-%20Battling%20and%20Pickup.md), set `pickup` false.
