### ISSUE TITLE
shiny and block list webhooks not showing up 

### ISSUE THREAD

**Issue by johnnieb333** [40Cakes/pokebot-gen3#275]
I have not gotten a shiny webhook for any shiny since last night at 8 pm . ive has the bots running for almost 5 hours and I get the millstone hooks but not the shiny

**Comment by Grifonzo** [comment]
ever since I updated my bot earlier this morning, I only get milestone hooks. I have found over 10 shines with no hooks and i've tried everything to fix it from redoing my settings to entirely redownloading the bot and nothing has worked.
