### ISSUE TITLE
issue with Card for Regirock, Registeel, and Regice

### ISSUE THREAD

**Issue by MojoJackk** [40Cakes/pokebot-gen3#348]
Hello, I would like to report an issue with the Bot. Currently, the Bot does not create shiny cards in the screenshots/cards folder and discord card notification for the following Pokémon: Regirock, Registeel, and Regice.

**Comment by pekempy** [comment]
Fixed in [37df8f8](https://github.com/40Cakes/pokebot-gen3/commit/37df8f8bc41760426dc76ee2564c885ef35bb06a)
