### ISSUE TITLE
Emulation Speed Options

### ISSUE THREAD

**Issue by Samushle** [40Cakes/pokebot-gen3#352]
Add more options to "Emulations Speed." Faster than 4x speed, but not unthrottled due to overheating of the CPU. 
Maybe a custom emulation speed that lets you choose what speed you want. 4x is too slow but unthrottled starts to overheat my PC with like 30x speeds and my fans need to be on full blast to control the temperature.

**Comment by 40Cakes** [comment]
Resolved in #362.
