### ISSUE TITLE
the bot continue hunting even after shiny

### ISSUE THREAD

**Issue by Boosolomon** [40Cakes/pokebot-gen3#354]
So as the title the used to stop when it finds a shiny and there was a desktop notification, but with newer versions the bot works indefinitly when it finds a shiny it trys to catch it and continue, is there a way for the bot to stop as in the old versions.

**Comment by pekempy** [comment]
Set [auto-catch](https://github.com/40Cakes/pokebot-gen3/blob/main/wiki/pages/Configuration%20-%20Battling%20and%20Pickup.md#auto-catching) to `false` if you want it to stop on shinies.

**Comment by Boosolomon** [comment]
> Set [auto-catch](https://github.com/40Cakes/pokebot-gen3/blob/main/wiki/pages/Configuration%20-%20Battling%20and%20Pickup.md#auto-catching) to `false` if you want it to stop on shinies.

thanks
