### ISSUE TITLE
Starters mode has a large delay when selecting the starter

### ISSUE THREAD

**Issue by Schmollanski** [40Cakes/pokebot-gen3#67]
I ran the bot for about 4500 encounters but the time the bot took to select the starter has increased reset by reset, seemingly a frame per reset. This is very noticable at 1x speeds but after some time it also is noticable even at unbound speeds.

https://github.com/40Cakes/pokebot-gen3/assets/91688015/ec715d98-2f8d-4261-a85c-30ac68568392

**Comment by Terasol** [comment]
For Pokemon Emerald this is intended behaviour.
The RNG of the game isn't set to a random value on startup.
So every time the bot resets the game you would get the exact same pokemon when not waiting additional frames.

To circumvent that the bot is actively searching for frames with a RNG value that it hasn't seen yet to avoid finding duplicated starters.

In the [Cheats](https://github.com/40Cakes/pokebot-gen3#cheatsyml---cheats-config) config you can set `starters_rng` to `true`, then the bot injects a in python generated random value every time to speed up the process.

if you don't want to do that you will need to periodically create a new save game to start with a new trainer id.

**Comment by 40Cakes** [comment]
Hi, thanks for the report but this is a non-issue as @Terasol mentioned, this is outlined under [Starters mode ](https://github.com/40Cakes/pokebot-gen3#-starters) in the readme:

> For modes that use soft resets such as starters, the bot will track RNG to ensure a unique frame is hit after every reset, this is to prevent repeatedly generating an identical Pokémon, this will cause soft resets to take progressively longer over time

> If resets begin to take too long, it is recommended to start a new save file with a different TID to reset this delay or check out [profiles/cheats.yml](https://github.com/40Cakes/pokebot-gen3#cheatsyml---cheats-config)
