### ISSUE TITLE
Config rework

### ISSUE THREAD

**Issue by 40Cakes** [40Cakes/pokebot-gen3#69]
# Config Rework

Config is currently [handled fairly primitively](https://github.com/40Cakes/pokebot-gen3/blob/main/modules/config.py), as a dict that is imported wherever needed, should be converted to class/object. Also happy to discuss potentially better schema validation methods, but the current ones seem to work okay.

All files are loaded once at launch (except for catch_block.yml which is reloaded on every shiny encounter) and never again, which means users need to restart the bot for config changes to take effect - potentially look at polling files on an interval for changes with `os.stat(filename).st_mtime`?
```
config["general"]["bot_mode"] -> config.general.bot_mode
```

Allowing config to be overridden programatically or via CLI args for the bot session should enable easier automated bot tests (this should not overwrite the .yml config files).
```
python .\pokebot.py --config.general.bot_mode="spin"
```

### Required
- [ ] Convert config dict to class/object
- [ ] Override config with CLI args

### Optional
- [ ] Reload config on file change without requiring a bot restart
- [ ] Config editor in the GUI

## Notes
This issue has been raised to track the work/progress for this new feature/functionality.

Please keep your PR in draft until it is ready to be reviewed and tested. Referencing this issue in your PR description will allow for collaboration among many, and also just lets us know you're working on it, potentially saving someone else from wasting their time working on the same thing separately.

Don't be afraid to use this issue or visit the Discord channel [#development-chat🛠](https://discord.com/channels/1057088810950860850/1111076425559199787) to ask for help or discuss ideas related to this issue.

**Comment by unixtreme** [comment]
You can setup a watchdog to monitor the relevant file/s for changes, but I think reloading the config can be prone to tons of user input errors, and some text editors will gradually save which may cause the program to load the config with invalid values (e.g. the user isn't done modifying the file or is just playing around with it).

The most sensible way would probably be a GUI button/keyboard shortcut that allows reloading config files, ideally, this would first validate the new config is valid, and if not display an error and preserve the old config so the bot keeps running.

**Comment by unixtreme** [comment]
As for the configuration object itself, I've seen many different designs over the years but my favorite one so far is a class that holds all config and access to it (as well as validation), that provides some sort of method to fetch a particular config key without having to manually traverse the tree. The advantage of this is that all config validations can be centralized as well as all access to config data.

A rough example of what I mean would be say accessing `config["obs"]["http_server"]["ip"]` via a method in a `Config` instance
like `config.get(['obs', 'http_server', 'ip'])` this `get` method would validate that every expected object in the tree actually exists. It could even have an argument like `strict: bool` to dictate behavior in case of missing data, maybe in some cases the data not being present does not matter, but maybe in others we want it to raise an exception.
