### ISSUE TITLE
Gift Pokémon modes

### ISSUE THREAD

**Issue by 40Cakes** [40Cakes/pokebot-gen3#86]
# Gift Pokémon Modes

Create bot modes for unique static/gift Pokémon:
[List of in-game event Pokémon (Emerald)](https://bulbapedia.bulbagarden.net/wiki/List_of_in-game_event_Pok%C3%A9mon_(Emerald))

### Wynaut
The old woman by the sand baths in [Lavaridge Town](https://bulbapedia.bulbagarden.net/wiki/Lavaridge_Town) will give the player a [Wynaut](https://bulbapedia.bulbagarden.net/wiki/Wynaut_(Pok%C3%A9mon)) [Egg](https://bulbapedia.bulbagarden.net/wiki/Pok%C3%A9mon_Egg).

### Castform
The staff of the [Weather Institute](https://bulbapedia.bulbagarden.net/wiki/Weather_Institute) will give the player a [Castform](https://bulbapedia.bulbagarden.net/wiki/Castform_(Pok%C3%A9mon)) for saving the facility from [Team Aqua](https://bulbapedia.bulbagarden.net/wiki/Team_Aqua).

### Fossil Pokémon
The player may choose between the [Root](https://bulbapedia.bulbagarden.net/wiki/Root_Fossil) and [Claw Fossils](https://bulbapedia.bulbagarden.net/wiki/Claw_Fossil) in the [Mirage Tower](https://bulbapedia.bulbagarden.net/wiki/Mirage_Tower), while the other fossil will be available to them in the [Desert Underpass](https://bulbapedia.bulbagarden.net/wiki/Desert_Underpass) after entering the [Hall of Fame](https://bulbapedia.bulbagarden.net/wiki/Hall_of_Fame). The fossils can be revived into [Lileep](https://bulbapedia.bulbagarden.net/wiki/Lileep_(Pok%C3%A9mon)) and [Anorith](https://bulbapedia.bulbagarden.net/wiki/Anorith_(Pok%C3%A9mon)) at the [Devon Corporation](https://bulbapedia.bulbagarden.net/wiki/Devon_Corporation) headquarters in [Rustboro City](https://bulbapedia.bulbagarden.net/wiki/Rustboro_City).

### Beldum
After the player has entered the Hall of Fame, [Steven](https://bulbapedia.bulbagarden.net/wiki/Steven_Stone) will leave a [Beldum](https://bulbapedia.bulbagarden.net/wiki/Beldum_(Pok%C3%A9mon)) as a gift for them in his cottage in [Mossdeep City](https://bulbapedia.bulbagarden.net/wiki/Mossdeep_City).

### Sudowoodo
[Sudowoodo](https://bulbapedia.bulbagarden.net/wiki/Sudowoodo_(Pok%C3%A9mon)) is located in the southeast section of the [Battle Frontier](https://bulbapedia.bulbagarden.net/wiki/Battle_Frontier_(Generation_III)). Much like in [Generation II](https://bulbapedia.bulbagarden.net/wiki/Generation_II) games, NPCs will talk about it as a tree. However, when the player uses the [Wailmer Pail](https://bulbapedia.bulbagarden.net/wiki/Wailmer_Pail) on it, it will spring to life.

### Required
- [x] Wynaut
- [x] Castform
- [x] Fossil Pokémon
- [x] Beldum
- [x] Sudowoodo

### Optional
- [ ] Any cheats/memhacks to make the modes faster (toggleable)

## Notes
This issue has been raised to track the work/progress for this new feature/functionality.

Please keep your PR in draft until it is ready to be reviewed and tested. Referencing this issue in your PR description will allow for collaboration among many, and also just lets us know you're working on it, potentially saving someone else from wasting their time working on the same thing separately.

Don't be afraid to use this issue or visit the Discord channel [#development-chat🛠](https://discord.com/channels/1057088810950860850/1111076425559199787) to ask for help or discuss ideas related to this issue.

**Comment by PeteKempDojo** [comment]
Note for **Castform** method - In order to get the game into a state for SRing, you must save **before** the Team Aqua battle, and use PKHeX to **completely fill** your PC, and party.
If any spaces are in your party or any PC box, Castform will be force-gifted to you upon completion of the fight.

Doing this correctly will mean you can save before speaking to the staff to receive the Castform, and can S/R it as normal.

**Comment by pekempy** [comment]
[x] Sudowoodo in PR #170 
[x] Castform in PR #171 
[x] Fossil Pokemon (FRLG AND RSE) in PR #171 
[x] Beldum in PR #171 
[ ] Wynaut Untested but may work in #171 though no hatching functionality for non-cheat
